Repository algorand/js-algorand-sdk, pull requests merged in 2021-07, with the labels that each got.

#397 Support transactions with a first round of zero
  .eslintrc.js
  src/client/client.ts
  src/encoding/uint64.ts
  src/makeTxn.ts
  src/multisig.ts
  src/transaction.ts
  tests/5.Transaction.js
  tests/6.Multisig.js
  tests/cucumber/steps/steps.js
Labels: Team Scytale, Unplanned, bug

#400 Add `prepare` script to support npm installing with the git URL
  package.json
Labels: Team Scytale, Unplanned

#405 Regenerate code with the latest specification file (b1aba664)
  src/client/v2/algod/models/types.ts
Labels: generated
