Repository algorand/js-algorand-sdk, pull requests merged in 2022-11, with the labels that each got.

#675 fix: mergeMultisigTransactions logic error
  src/multisig.ts
  tests/6.Multisig.ts
Labels: Bug-Fix

#604 Boxes: Add support for Boxes
  src/boxStorage.ts
  src/client/client.ts
  src/client/v2/algod/algod.ts
  src/client/v2/algod/getApplicationBoxByName.ts
  src/client/v2/algod/getApplicationBoxes.ts
  src/client/v2/algod/models/types.ts
  src/client/v2/indexer/indexer.ts
  src/client/v2/indexer/lookupApplicationBoxByIDandName.ts
  src/client/v2/indexer/models/types.ts
  src/client/v2/indexer/searchForApplicationBoxes.ts
  src/client/v2/jsonrequest.ts
  src/composer.ts
  src/makeTxn.ts
  src/transaction.ts
  src/types/transactions/application.ts
  src/types/transactions/base.ts
  src/types/transactions/encoded.ts
  src/types/transactions/index.ts
  tests/5.Transaction.js
  tests/cucumber/integration.tags
  tests/cucumber/steps/steps.js
  tests/cucumber/unit.tags
Labels: New Feature

#683 Release: merge back into develop Release/v1.23.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: Skip-Release-Notes

#684 CI: Remove unneeded dependency & update package-lock
  package-lock.json
  package.json
Labels: Bug-Fix

#693 Tests: Migrate v1 algod dependencies to v2 in cucumber tests
  tests/cucumber/steps/steps.js
Labels: Enhancement

#696 REST API: Add KV counts to NodeStatusResponse
  src/client/v2/algod/models/types.ts
Labels: Enhancement

#694 Fix: createMultisigTransaction name in comments
  src/multisig.ts
Labels: Enhancement

#698 Enhancement: allowing zero-length static array
  src/abi/abi_type.ts
  tests/10.ABI.ts
Labels: Enhancement

#700 Bug-Fix: encode ABI string with non-ASCII characters
  src/abi/abi_type.ts
  tests/10.ABI.ts
Labels: Bug-Fix

#701 ABI: Refactor ABI encoding test to round-trip
  tests/10.ABI.ts
Labels: Enhancement
