Repository algorand/js-algorand-sdk, pull requests merged in 2022-09, with the labels that each got.

#642 Enhancement: Add deprecation tag to algod v1 client
  src/client/algod.js
Labels: Enhancement

#652 enhancement: add unit test for ParticipationUpdates field
  tests/cucumber/unit.tags
Labels: Enhancement, Team Lamprey

#572 Bug-Fix: Fix typo in documentation for `searchAccounts` `currencyGreaterThan`
  src/client/v2/indexer/searchAccounts.ts
Labels: Bug-Fix
