Repository algorand/js-algorand-sdk, pull requests merged in 2022-07, with the labels that each got.

#603 FOR REVIEW ONLY - Release v1.18.1
  CHANGELOG.md
  FAQ.md
  README.md
  package-lock.json
  package.json
  src/client/urlTokenBaseHTTPClient.ts
  src/dryrun.ts
  src/utils/utils.ts
  tests/2.Encoding.js
  webpack.config.js
Labels: Bug-Fix

#600 Github-Actions: Adding PR title and label checks
  .github/release.yml
  .github/workflows/pr-type-category.yml
Labels: Enhancement

#607 tech-debt: Remove unused/unmaintained templates
  templates/Dockerfile
  templates/common_config.properties
  templates/generate.sh
  templates/model.vm
  templates/model_filename.vm
  templates/parameter_order_overrides.properties
Labels: Bug-Fix

#608 Box Storage: Add GetApplicationBoxes API and cucumber steps
  src/client/v2/algod/algod.ts
  src/client/v2/algod/getApplicationBoxes.ts
  src/client/v2/algod/models/types.ts
  tests/cucumber/steps/steps.js
Labels: New Feature

#605 Enhancement: Upgrade typedoc and plugins
  package-lock.json
  package.json
  typedoc.config.json
Labels: New Feature

#595 API: Support attaching signatures to standard and multisig transactions
  src/main.ts
  src/multisig.ts
  src/nacl/naclWrappers.ts
  src/transaction.ts
  tests/4.Utils.ts
  tests/6.Multisig.ts
  tests/7.AlgoSDK.js
Labels: Enhancement, Team Scytale
