Repository algorand/js-algorand-sdk, pull requests merged in 2023-03, with the labels that each got.

#743 algod: Simulate Endpoint
  src/client/v2/algod/algod.ts
  src/client/v2/algod/models/types.ts
  src/client/v2/algod/simulateTransaction.ts
  src/composer.ts
  src/encoding/encoding.ts
  src/signer.ts
  src/transaction.ts
  tests/cucumber/integration.tags
  tests/cucumber/steps/steps.js
Labels: Enhancement

#749 algod: Minor improvements to simulation support
  src/client/v2/algod/simulateTransaction.ts
  src/composer.ts
  tests/cucumber/steps/steps.js
Labels: Team Scytale, Bug-Fix

#755 Docs: Repair the links in the docs to developer.algorand.org
  src/client/v2/algod/algod.ts
  src/client/v2/algod/getApplicationBoxByName.ts
  src/client/v2/algod/getApplicationBoxes.ts
Labels: Bug-Fix

#757 Fix: allow nonParticipation flag to be a boolean
  src/makeTxn.ts
Labels: Bug-Fix
