Repository algorand/js-algorand-sdk, pull requests merged in 2023-04, with the labels that each got.

#760 BugFix: min fee sp fix
  src/client/v2/algod/suggestedParams.ts
  src/types/transactions/base.ts
Labels: Bug-Fix

#764 API: Support updated simulate endpoint
  src/client/v2/algod/algod.ts
  src/client/v2/algod/models/types.ts
  src/client/v2/algod/simulateTransaction.ts
  src/transaction.ts
  tests/cucumber/steps/steps.js
Labels: Enhancement

#769 algod: Add blockOffsetTimestamp, syncRound APIs to algod client
  src/client/v2/algod/algod.ts
  src/client/v2/algod/getBlockOffsetTimestamp.ts
  src/client/v2/algod/getSyncRound.ts
  src/client/v2/algod/models/types.ts
  src/client/v2/algod/ready.ts
  src/client/v2/algod/setBlockOffsetTimestamp.ts
  src/client/v2/algod/setSyncRound.ts
  src/client/v2/algod/unsetSyncRound.ts
  tests/cucumber/integration.tags
  tests/cucumber/steps/index.js
  tests/cucumber/steps/steps.js
  tests/cucumber/unit.tags
Labels: Enhancement

#768 Simulation: Lift log limits option in SimulateRequest
  src/client/v2/algod/simulateTransaction.ts
  src/composer.ts
  tests/cucumber/integration.tags
  tests/cucumber/steps/steps.js
Labels: New Feature
