Repository algorand/js-algorand-sdk, pull requests merged in 2023-08, with the labels that each got.

#807 bug-fix: include currency-greater-than param for 0 value
  .test-env
  package-lock.json
  package.json
  src/client/v2/indexer/lookupAccountTransactions.ts
  src/client/v2/indexer/lookupAssetBalances.ts
  src/client/v2/indexer/lookupAssetTransactions.ts
  src/client/v2/indexer/searchAccounts.ts
  src/client/v2/indexer/searchForTransactions.ts
  tests/cucumber/steps/steps.js
Labels: Team Lamprey, Bug-Fix

#803 Simulation: Execution trace (PC/Stack/Scratch) support
  src/client/v2/algod/models/types.ts
  tests/cucumber/integration.tags
  tests/cucumber/steps/steps.js
Labels: New Feature

#811 CICD: Update chromedriver in package.json to 116+
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Enhancement

#813 Text: Fix pre-release-version description in create-release-pr workflow
  .github/workflows/create-release-pr.yml
Labels: Team Hyper Flow, Skip-Release-Notes

#776 3.0.0: Convert algod responses to typed
  examples/app.ts
  examples/asa.ts
  examples/atc.ts
  examples/block_fetcher/index.ts
  examples/debug.ts
  examples/overview.ts
  examples/utils.ts
  package-lock.json
  package.json
  src/client/client.ts
  src/client/v2/algod/accountApplicationInformation.ts
  src/client/v2/algod/accountAssetInformation.ts
  src/client/v2/algod/accountInformation.ts
  src/client/v2/algod/algod.ts
  src/client/v2/algod/block.ts
  src/client/v2/algod/compile.ts
  src/client/v2/algod/disassemble.ts
  src/client/v2/algod/dryrun.ts
  src/client/v2/algod/getApplicationByID.ts
  src/client/v2/algod/getAssetByID.ts
  src/client/v2/algod/getBlockHash.ts
  src/client/v2/algod/getLedgerStateDelta.ts
  src/client/v2/algod/getTransactionGroupLedgerStateDeltasForRound.ts
  src/client/v2/algod/getTransactionProof.ts
  src/client/v2/algod/lightBlockHeaderProof.ts
  src/client/v2/algod/pendingTransactionInformation.ts
  src/client/v2/algod/pendingTransactions.ts
  src/client/v2/algod/pendingTransactionsByAddress.ts
  src/client/v2/algod/sendRawTransaction.ts
  src/client/v2/algod/setBlockOffsetTimestamp.ts
  src/client/v2/algod/setSyncRound.ts
  src/client/v2/algod/simulateTransaction.ts
  src/client/v2/algod/stateproof.ts
  src/client/v2/algod/status.ts
  src/client/v2/algod/statusAfterBlock.ts
  src/client/v2/algod/suggestedParams.ts
  src/client/v2/algod/supply.ts
  src/client/v2/algod/versions.ts
  src/client/v2/serviceClient.ts
  src/composer.ts
  src/dryrun.ts
  src/makeTxn.ts
  src/utils/utils.ts
  src/wait.ts
  tests/5.Transaction.js
  tests/cucumber/steps/steps.js
Labels: Enhancement
