Repository algorand/js-algorand-sdk, pull requests merged in 2023-09, with the labels that each got.

#818 Simulate: Application State Change and Hash of Executed Bytecode
  src/client/v2/algod/models/types.ts
  tests/cucumber/integration.tags
  tests/cucumber/steps/steps.js
Labels: New Feature

#827 node: Update to node 18, drop support for node 16
  .circleci/config.yml
  package-lock.json
  package.json
  tests/cucumber/docker/Dockerfile
Labels: Enhancement

#826 api: Regenerate client.
  src/client/v2/algod/algod.ts
  src/client/v2/algod/getBlockTxids.ts
  tests/cucumber/steps/steps.js
  tests/cucumber/unit.tags
Labels: Enhancement

#828 DevOps: Update release PR generator to nodejs 18
  .github/workflows/create-release-pr.yml
Labels: Team Hyper Flow, Skip-Release-Notes
