Repository algorand/js-algorand-sdk, pull requests merged in 2023-05, with the labels that each got.

#773 node: Drop support for node v14, npm audit fix
  .circleci/config.yml
  package-lock.json
  package.json
  tests/cucumber/docker/Dockerfile
Labels: Enhancement

#772 client: Export token header types
  src/main.ts
Labels: Enhancement

#775 DevOps: Add CODEOWNERS to restrict workflow editing
  .github/workflows/pr-type-category.yml
  CODEOWNERS
Labels: Enhancement, Team Hyper Flow

#774 Docs: Update README & FAQ
  FAQ.md
  README.md
Labels: Enhancement

#780 docs: fix error message
  src/composer.ts
Labels: Bug-Fix

#783 DevOps: Update CODEOWNERS to only refer to the devops group
  CODEOWNERS
Labels: Enhancement, Unplanned, Team Hyper Flow

#782 Client: Don't send auth header when token is empty
  src/client/v2/serviceClient.ts
  tests/9.Client.ts
  tests/cucumber/steps/index.js
  tests/cucumber/steps/steps.js
  tests/cucumber/unit.tags
Labels: Enhancement

#784 Algod: Simulation run with extra budget per transaction group
  src/client/v2/algod/models/types.ts
  tests/cucumber/integration.tags
  tests/cucumber/steps/steps.js
Labels: New Feature

#786 Enhancement: Verbose Harness
  .test-env
Labels: Skip-Release-Notes

#785 algod: Add state delta APIs
  src/client/v2/algod/algod.ts
  src/client/v2/algod/getLedgerStateDelta.ts
  src/client/v2/algod/getLedgerStateDeltaForTransactionGroup.ts
  src/client/v2/algod/getTransactionGroupLedgerStateDeltasForRound.ts
  src/client/v2/algod/models/types.ts
  tests/cucumber/steps/steps.js
  tests/cucumber/unit.tags
Labels: Enhancement

#787 deps: Remove coveralls, mocha lcov
  package-lock.json
  package.json
Labels: Enhancement

#789 community: Create CODE_OF_CONDUCT.md
  .prettierignore
  CODE_OF_CONDUCT.md
Labels: Skip-Release-Notes
